language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - 51101661@qq.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d")-$TRAVIS_BUILD_NUMBER
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
env:
  global:
  - secure: NDepWTti/8ErBDrV+jPiq4M74yMkBDnX73TRsKENuNvCSfGIDSkaXJ1Xmy6KPFojfSPLmlhfBUqIvP934lOD4itI83qroj32T5Jk2EEagT2OMTrQTKIEAwwQzFlgmKFE4neQxga3La0DJ+c82gTNwW/8xfaK+P3bWFK+/km/97f9p9oI3rWoMoOvDCaU5SV4wUyprnBrNNOPhgecKS4Z3AVv+B9lMaszFGdN6FwC7MceTfPBwjI4+Fzlsk3ffgHvtTAtcrS2AiVFn1DnLEktwF3HUk9ViMCL8WU4mN9QMj8EpMbqvl3X0AWF1hTrOCtN3cjfGk+1vNReEYhBW4MtGrEQ0/kUGJu6/s8TfdefUFG4omIPzvfjM1AzQlNpZzxQYcNCBcT8gNBK4Y/2ssKdSUWjBZ4OmtMMy3cLo252zz4VyFeZRlYZDrC7/H1wPiUyoFWG8dTi42f7jEzQGyv2ov34QRbW/mtC53wBNEAwQv7hIuA6BlpNF0D9fqOk46zaqXY3uofA4+2sgDkzgwINrCmy93f5e3ZR+J52e2PEJp33nW49V0hC1UXBiDgavy3rKdEGpcTQ4IQcL8lhv7pcoVAwdxRznSQcwqd/BLVa/MVlLMYxl5fs9ui66+BM4Tv3XIT9D5DaEXPl81nHvXXkSkpT+Qdbd0G7BdztO5pHk64=
  - secure: szSiUDT8enT0EFI7gEPauWd4o1BK65kAq72d/cc9BvqFFWpuTRPL1A5S6xucf88gRAw8AytQrErOV1OZlQZH+4yZDj40pmNxJrttZ9DnD0ypZKKW5TaFJSMorRK/O5ZrdVLE+dtvaJOVtSR3K/yt01PNUCeoBwcQ0UqPjb8DE57lk5WD8Cy1Y6AtdHr27zr1oVe4Ts3J31VgVcyZbSqpdSeR/+ZI8KjI1hEAmSGBdy2HNwSifkOltI/qq4HuoIy9heUvbWrf1a6ZovaiTPRcAx4ESnLtGpKH4znJ5fYQuofwdYtmBG45dmY4ZQVuLookbie/3J5QVfcjs0DQWPHl7nwEMOnXGb8Fn2TdrRv+bBM+yndOshZNLYoeFK1BOKBExp6Ujp2keH/B7PGGdcsVkFgV0KtN4f4pLOR49NiLeDK6ZKh1P4l2qic/QiVXHnGp9nrpn+opfOXpzXCVincoohH2YaifSp4KsFBUhG2f4E/O0xoA0Vk8f6L0NxH9ZYp6rryfOylVeq1/nUjHf4P/4/sNCOlpUy9/rF90OyJEEVpms7Pt0dgwRNRNCnJ9/qUrs1HPJVTjcApwnmcyNkE3OoGDl8I6gT8ilLXWtd57EO9iFdETR6u9DXvPhO1PQkZSGDB9SEu+hXMnbBUN/+PJ6lV7LZq/FbdQ5vT+26YSCTI=
  - secure: V8QgtxtVKsYJjeM6JxWG0mOFJeCkNuQBMYPy1HLsiQRMJFRXOd/K4O8FbZf01Caq1g1+CdgttuG2i85ESFib+mqv9p75likt7SYS/zcuWePsgD1s9fRjlwp2JGrT4ZmzYnsiZz3h0FQCD/HQWwIKTpL3f6lwGsZlQiut4xTJlmcyvnoj4r1nzA342RujwtZQupaCVedLT5mBBGrNFGkfvlJPKpVejINIJHdXx33J1jTGR+QmsYQzTpazuewxKPciTaHguBLKenq8C2O/q8jULNOifE57dzZkc1WDp4iixy9w2hP9Qbj6gIj7nY9U01UNqdMYxnh+eNEVJHBReF5HtsBAK0aarTDGtge55rz1e8hrQ+xd6kUPuhxHstrujgx+muGsNKQikZIoUOilWsgwtB/2JoBC2a/EpH7/QMiLBih1J/y6I3+lWakcCNjusfHQjSiXj/0Vs3c2qyCak2duSJbc5YLYybef8yniCeNpuIifB0bn2odmBeyMfqS+9I7LS6pck5KUfYn84SIDcAp2cVPZgLguh+56EjX6RIekaP/dsiaCkrpWo/5GcExmO3iw5oPiwhhmWxbpIwba/ajNRtVAsGPDaydHRsLBzoAcMKHwtSb7u3mEznAe0OEsPpU1fYrQijM+dfmOLJIFkWeS9do6skCmBAdQ17ThhQWsll8=
